version: '3.8'

services:
  ptk_rabbitmq:
    image: rabbitmq:3-management
    container_name: ptk_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres_customers:
    image: postgres:15
    container_name: postgres_customers
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_customers_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  postgres_orders:
    image: postgres:15
    container_name: postgres_orders
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_orders_data:/var/lib/postgresql/data
    ports:
      - '5434:5432'

  postgres_products:
    image: postgres:15
    container_name: postgres_products
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pg_products_data:/var/lib/postgresql/data
    ports:
      - '5435:5432'

volumes:
  rabbitmq_data:
  pg_customers_data:
  pg_orders_data:
  pg_products_data:
